[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python -c \"import nltk; nltk.download('stopwords'); nltk.download('punkt'); nltk.download('wordnet')\""
]

[start]
cmd = "gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
